name: coffsy_movie_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 13.0.4+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #Modules
  tv_show:
    path: libraries/modules/tv_show
  movie:
    path: libraries/modules/movie
  about:
    path: libraries/modules/about
  discover:
    path: libraries/modules/discover
  #Core Modules
  core:
    path: libraries/core
  dependencies:
    path: libraries/dependencies
  coffsy_design_system:
    path: libraries/coffsy_design_system
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  dartz: ^0.10.0

dev_dependencies:
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  win32: ^5.10.0  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/movie_icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
    - shorebird.yaml

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSans-Italic.ttf
          style: italic
        - asset: assets/fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
