include: package:flutterando_analysis/flutter_package.yaml
linter:
  rules:
    prefer_single_quotes: true
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_print: true
    one_member_abstracts: true
    prefer_const_constructors: true
    avoid_classes_with_only_static_members: false

analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
  rules:       
    - avoid-redundant-async
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters    
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - prefer-moving-to-variable
    